#!/usr/bin/env node
// Downloads one square artwork per collection into img/, and writes art.js.
//
// Two sources, in order:
//   1. OpenSea. Its per-collection endpoint is public (no key) and its CDN takes
//      a ?w= parameter, so this yields 512px. The slug is not in our data, so we
//      guess candidates from the CoinGecko id and keep whatever resolves —
//      a wrong slug returns 401, which is free to detect.
//   2. CoinGecko's own image, whose /original/ variant tops out at 250px.
//
// Blur mode draws the artwork at ~170px CSS, so 512 clears a 2x screen and 250
// is slightly soft — acceptable, because the image is only fully sharp on the
// last guess. Resolved slugs are cached so re-runs skip the lookup.
const fs = require('fs'), path = require('path');
const T = __dirname, IMG = path.join(T, '..', 'img');
const cache = JSON.parse(fs.readFileSync(path.join(T, '.cg-cache.json'), 'utf8'));
const SLUGS = path.join(T, '.os-slugs.json');
let slugs = {}; try { slugs = JSON.parse(fs.readFileSync(SLUGS, 'utf8')); } catch {}
const only = process.argv.includes('--missing');

fs.mkdirSync(IMG, { recursive: true });
const sleep = ms => new Promise(r => setTimeout(r, ms));

// candidate OpenSea slugs for a CoinGecko id, most likely first
function candidates(id) {
  const base = id.replace(/-\d{6,}$/, '');            // strip CG's disambiguating suffix
  const c = [base, base.replace(/-/g, ''), base.replace(/-official$/, ''),
             base.replace(/^the-/, ''), base + '-official'];
  return [...new Set(c)];
}

async function osImage(id) {
  if (slugs[id] !== undefined) {
    return slugs[id] ? slugs[id].img : null;          // null = known miss
  }
  for (const s of candidates(id)) {
    try {
      const r = await fetch(`https://api.opensea.io/api/v2/collections/${s}`, { signal: AbortSignal.timeout(15000) });
      if (r.ok) {
        const d = await r.json();
        if (d && d.image_url) {
          slugs[id] = { slug: s, img: d.image_url };
          fs.writeFileSync(SLUGS, JSON.stringify(slugs, null, 1));
          return d.image_url;
        }
      }
    } catch {}
    await sleep(350);
  }
  slugs[id] = null; fs.writeFileSync(SLUGS, JSON.stringify(slugs, null, 1));
  return null;
}

async function grab(url, dest) {
  // Every network call here is best-effort: a CDN that times out costs this
  // collection its artwork and nothing else, so nothing is allowed to throw
  // out of the loop and abandon the images already downloaded.
  try {
    const r = await fetch(url, {
      headers: { 'user-agent': 'mintdle/1.0' },
      signal: AbortSignal.timeout(20000)
    });
    if (!r.ok) return 0;
    const b = Buffer.from(await r.arrayBuffer());
    if (b.length < 500) return 0;
    fs.writeFileSync(dest, b);
    return b.length;
  } catch { return 0; }
}

(async () => {
  const ids = Object.keys(cache);
  let os = 0, cg = 0, skip = 0, fail = 0;
  for (const id of ids) {
    const dest = path.join(IMG, id + '.img');
    if (only && fs.existsSync(dest)) { skip++; continue; }
    let n = 0, via = '';
    let u = null;
    try { u = await osImage(id); } catch {}
    if (u) { n = await grab(u + (u.includes('?') ? '&' : '?') + 'w=512', dest); if (n) { os++; via = 'opensea 512'; } }
    if (!n && cache[id].img) {
      const c = cache[id].img.replace('/small_2x/', '/original/').replace('/small/', '/original/');
      n = await grab(c, dest); if (n) { cg++; via = 'coingecko 250'; }
    }
    if (!n) { fail++; console.log(`  ✗ ${id}`); }
    else console.log(`  ✓ ${id} · ${via} · ${(n / 1024).toFixed(0)}kb`);
  }
  // art.js maps a collection key to its file. game.js falls back to a drawn
  // placeholder for anything missing, so a gap here is cosmetic, not fatal.
  const have = fs.readdirSync(IMG).filter(f => f.endsWith('.img')).map(f => f.slice(0, -4));
  const man = have.reduce((a, k) => (a[k] = 'img/' + k + '.img', a), {});
  fs.writeFileSync(path.join(T, '..', 'art.js'),
    '// generated by tools/fetch-art.js — collection key -> artwork file\n' +
    '// Files carry a neutral .img extension: the sources mix png, jpg and webp,\n' +
    '// and browsers sniff content, so one extension avoids a lying filename.\n' +
    'var ART = ' + JSON.stringify(man, null, 1) + ';\n');
  console.log(`\n${os} from OpenSea · ${cg} from CoinGecko · ${skip} skipped · ${fail} failed · art.js has ${have.length}`);
  // cap the handful of oversized originals before they reach a player
  try { require('child_process').execSync('node ' + JSON.stringify(path.join(T, 'normalize-art.js')), { stdio: 'inherit' }); } catch {}
})();
